In [2]:
pip install numpy

In [3]:
import numpy as np

## Creating arrays using list

In [4]:
myList = [1,2,3,4,5,6]
np.array(myList)

array([1, 2, 3, 4, 5, 6])

In [5]:
myNestedList = [[1,2,3], [2,3,4],[4,5,6]]
np.array(myNestedList)

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [6]:
myList1 = [2,3,4]
myList2 = [3,4,5]
np.array([myList1, myList2])

array([[2, 3, 4],
       [3, 4, 5]])

## Creating arrays using functions

In [7]:
np.arange(4,20) 

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
np.arange(4,50,5)

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.zeros(5, dtype= int)

array([0, 0, 0, 0, 0])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones(6, dtype= int)

array([1, 1, 1, 1, 1, 1])

In [13]:
np.full((4,5),10.6)

array([[10.6, 10.6, 10.6, 10.6, 10.6],
       [10.6, 10.6, 10.6, 10.6, 10.6],
       [10.6, 10.6, 10.6, 10.6, 10.6],
       [10.6, 10.6, 10.6, 10.6, 10.6]])

In [14]:
np.full((5,5), 20, dtype =float)

array([[20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.]])

In [15]:
np.info(np.ones)

 ones(shape, dtype=None, order='C')

Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and order.

See Also
--------
ones_like : Return an array of ones with shape and type of input.
empty : Return a new uninitialized array.
zeros : Return a new array setting values to zero.
full : Return a new array of given shape filled with value.


Examples
--------
>>> np.ones(5)
array([1., 1., 1., 1., 1.])

>>> np.ones((5,), dtype=int)
array([1, 1, 1, 1, 1])

>>> np.ones((2, 1))
array([[1.],
       [1.]])

>>> s = (2,2

In [16]:
x = np.array([1,2,0])
print(x)
np.all(x)

[1 2 0]


False

In [17]:
np.any(x)

True

In [18]:
a = np.array([0,2,3, np.nan, np.inf])
a

array([ 0.,  2.,  3., nan, inf])

In [19]:
np.isinf(a)

array([False, False, False, False,  True])

In [20]:
np.isnan(a)

array([False, False, False,  True, False])

In [21]:
c = np.array([1+3j, 4, 3+7j, 8,9])
c

array([1.+3.j, 4.+0.j, 3.+7.j, 8.+0.j, 9.+0.j])

In [22]:
np.iscomplex(c)

array([ True, False,  True, False, False])

In [23]:
np.isreal(c)

array([False,  True, False,  True,  True])

## Comparison of arrays

In [24]:
x = np.array([1,2,3,4])
y = np.array([2,1,3,5])

In [25]:
np.greater(x,y)

array([False,  True, False, False])

In [26]:
np.less(x,y)

array([ True, False, False,  True])

In [27]:
np.greater_equal(x,y)

array([False,  True,  True, False])

In [28]:
np.less_equal(x,y)

array([ True, False,  True,  True])

In [29]:
v = np.identity(6, dtype= int)
print(v)

v.shape

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


(6, 6)

In [30]:
np.random.normal(0,1)

0.8607663063748618

In [31]:
A = np.arange(10,22).reshape(2,6)
A

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

In [32]:
v = np.linspace(10,50, 10 , dtype = int)
v

array([10, 14, 18, 23, 27, 32, 36, 41, 45, 50])

In [33]:
np.random.randint(0,11,6)

array([10,  7,  1,  6,  9,  1])

## Calculations

In [34]:
x = np.array([2,3,4,5])
y = np.array([3,5,6,7])
multiply = x*y

In [35]:
multiply

array([ 6, 15, 24, 35])

In [36]:
np.diag([2,3,4,5])

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [37]:
x = np.arange(20,32).reshape(4,3)
print(x)
np.sum(x)

[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]]


306

In [38]:
np.sum(x , axis=0) # columns 

array([ 98, 102, 106])

In [39]:
np.sum(x , axis= 1) # rows

array([63, 72, 81, 90])

In [40]:
x = np.array([1,2])
y = np.array([3,4])
np.dot(x,y)

11

In [41]:
np.multiply(x,y)

array([3, 8])

In [42]:
np.outer(x,y)

array([[3, 4],
       [6, 8]])

In [43]:
np.zeros_like(x)

array([0, 0])

In [44]:
np.arange(10,55).reshape(3,5,3)

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]],

       [[40, 41, 42],
        [43, 44, 45],
        [46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]]])

In [45]:
np.__version__

'1.19.2'

## Broadcasting

In [46]:
newArr = np.arange(10)
newArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
newArr[:] = 20

In [70]:
newArr

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [72]:
newArr[3:6] = 500

In [73]:
newArr

array([ 20,  20,  20, 500, 500, 500,  20,  20,  20,  20])

## Copy

In [74]:
copy = newArr.copy()

In [75]:
copy

array([ 20,  20,  20, 500, 500, 500,  20,  20,  20,  20])

In [76]:
copy[:5] = 15

In [77]:
copy

array([ 15,  15,  15,  15,  15, 500,  20,  20,  20,  20])

## Sorting

In [78]:
unsorted = np.array([20,10,25,40,11])

In [79]:
unsorted.sort()

In [80]:
unsorted

array([10, 11, 20, 25, 40])

In [57]:
type(unsorted)

numpy.ndarray

## Indexing

In [81]:
arr2d = np.arange(25).reshape(5,5)

In [82]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [83]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [84]:
arr2d[1][4]

9

In [87]:
arr2d[1:3,3:]

array([[ 8,  9],
       [13, 14]])

In [63]:
arr2d[2:5,:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
arr2d[:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])

## Conditional

In [88]:
newArr = np.arange(1,11)

In [89]:
newArr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
newArr[newArr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [91]:
newArr[newArr==6]

array([6])