In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np #alias

## Creating array using list

In [6]:
myList = [1,2,3,4,5]
np.array(myList)

array([1, 2, 3, 4, 5])

In [4]:
myNestedList = [[1,2,3],[3,4,5],[5,6,7]]
np.array(myNestedList)

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [5]:
myList1 = [3,4,5]
myList2 = [3,4,5]
np.array([myList1,myList2])

array([[3, 4, 5],
       [3, 4, 5]])

## Creating arrays using Functions

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
np.zeros((3,4), dtype= 'int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
np.ones((4,3), dtype= 'int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
np.full((4,5),5.8)

array([[5.8, 5.8, 5.8, 5.8, 5.8],
       [5.8, 5.8, 5.8, 5.8, 5.8],
       [5.8, 5.8, 5.8, 5.8, 5.8],
       [5.8, 5.8, 5.8, 5.8, 5.8]])

## Comparison of arrays

In [20]:
x = np.array([1,2,3,4])
y = np.array([2,1,3,5])

In [19]:
np.greater(x,y)

array([False,  True, False, False])

In [21]:
np.less(x,y)

array([ True, False, False,  True])

In [22]:
np.greater_equal(x,y)

array([False,  True,  True, False])

In [23]:
np.less_equal(x,y)

array([ True, False,  True,  True])